import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  polifemo: [{ type: 'autogenerated', dirName: 'app' }],
  infra: [
    {
      type: 'autogenerated',
      dirName: 'infrastructure',
    },
  ],
}

export default sidebars
